// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmK-C_5upDB3vSuLN5gRbivxssMFgegbE',
    appId: '1:248037725510:android:e7d71453f7161716d60147',
    messagingSenderId: '248037725510',
    projectId: 'hoteljobbercandidate',
    databaseURL: 'https://hoteljobbercandidate.firebaseio.com',
    storageBucket: 'hoteljobbercandidate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCflmllUeM-l5Tnvivz3JntWzjfRvkWfjA',
    appId: '1:248037725510:ios:94be8d3c4cbbafded60147',
    messagingSenderId: '248037725510',
    projectId: 'hoteljobbercandidate',
    databaseURL: 'https://hoteljobbercandidate.firebaseio.com',
    storageBucket: 'hoteljobbercandidate.appspot.com',
    androidClientId:
        '248037725510-0bfq6kldahhvjal2rm9jo1to63n34klo.apps.googleusercontent.com',
    iosClientId:
        '248037725510-6md20k2naplqlk1807thtmr8g8hrcjn1.apps.googleusercontent.com',
    iosBundleId: 'com.hoteljobber.HoteljobberEmployeer',
  );
}
